USE FENG;

CREATE TABLE base_cobrancas (
    IDCOBRANCA INT PRIMARY KEY,
    IDCONTRATO INT,
    STATUS NCHAR(2),
    DATA_VENCIMENTO DATETIME,
    DATA_PAGAMENTO DATETIME,
    DATA_CANCELAMENTO DATETIME,
    VALOR_COBRANCA DECIMAL(10, 2),
    FOREIGN KEY (IDCONTRATO) REFERENCES base_contratos(IDCONTRATO)
);