USE FENG;

CREATE TABLE base_assinantes (
    IDASSINANTE INT PRIMARY KEY,
    SEXO NCHAR(1),
    DATA_NASCIMENTO DATETIME,
    ESTADO_CIVIL VARCHAR(20),
    ESCOLARIDADE VARCHAR(50),
    CIDADE VARCHAR(50),
    UF NCHAR(2)
);