USE FENG;

CREATE TABLE base_contratos (
    IDCONTRATO INT PRIMARY KEY,
    IDASSINANTE INT,
    PLANO NCHAR(1),
    FORMA_PAGAMENTO VARCHAR(20),
    DURACAO_PLANO INT,
    DATA_INICIAL DATETIME,
    DATA_FINAL DATETIME,
    FOREIGN KEY (IDASSINANTE) REFERENCES base_assinantes(IDASSINANTE)
);
