SELECT
    CT.PLANO,
    ROUND(SUM(BC.VALOR_COBRANCA) / COUNT(DISTINCT BC.IDCONTRATO), 2) AS TICKET_MEDIO
FROM 
    BASE_COBRANCAS BC,
    BASE_CONTRATOS CT
WHERE 
    BC.IDCONTRATO = CT.IDCONTRATO -- Relacionamento entre as tabelas
GROUP BY 
    CT.PLANO
ORDER BY 
    TICKET_MEDIO DESC
LIMIT 1;